export const ROOT = '/'
export const DASHBOARDS_PREFIX_PATH = '/dashboard'
export const FINANCE_PREFIX_PATH = '/dashboard/finance'
export const AUTH_PREFIX_PATH = '/auth'
export const LOGISTICS_PREFIX_PATH = '/dashboard/logistics'
export const INSIGHTS_PREFIX_PATH = '/dashboard/insights'
export const ADMINISTRATION_PREFIX_PATH = '/dashboard/administration'
export const DEVICE_MANAGEMENT_PREFIX_PATH = '/dashboard/device-management'