export const ROOT = '/'
export const DASHBOARDS_PREFIX_PATH = '/dashboard'
export const FINANCE_PREFIX_PATH = '/finance'
export const AUTH_PREFIX_PATH = '/auth'
export const LOGISTICS_PREFIX_PATH = '/logistics'
export const INSIGHTS_PREFIX_PATH = '/insights'
export const ADMINISTRATION_PREFIX_PATH = '/administration'